### ISSUE TITLE
Provide autowiring for cache provider

### ISSUE THREAD

**Issue by Soullivaneuh** [doctrine/DoctrineCacheBundle#140]
From https://github.com/doctrine/DoctrineBundle/issues/788 (sorry for the wrong project issue):

Would be great if we can have autowiring for cache provider such as:

```php
use Doctrine\Common\Cache\PredisCache;

final class RegistrarBridge
{
    /**
     * @var PredisCache
     */
    private $redisCache;

    public function __construct(PredisCache $redisCache)
    {
        $this->redisCache = $redisCache;
    }
```

Current workaround:

```php
$container->addAliases([
    \Doctrine\Common\Cache\PredisCache::class => 'doctrine_cache.providers.redis',
]);
```

**Comment by stof** [comment]
But you can have many providers of the same type, and you can have no providers of another type.

thus, you should probably not be typehinting a particular implementation, but interfaces, so that are the types to provide autowiring for in the bundle itself, if any.

**Comment by alcaeus** [comment]
I agree with @stof here - you should be type hinting an interface, not a concrete implementation. As such, it wouldn't make any sense **for us** to add autowiring aliases, this is better done in your app where you know that unless otherwise specified you want to wire provider `xyz` as the default cache implementation.

Closing this issue as `won't fix`. If you got more reasons why we should provide some aliases for autowiring, please let me know.
